### PR TITLE
Data and Geometry tutorial notebooks

### PR DESCRIPTION
**Pull request by gabeschoenbach**
Added `tutorials/data_tutorial.ipynb` and `tutorials/geometry_tutorial.ipynb` to test out our `evaltools.data` and `evaltools.geometry` submodules, respectively. These both rely on the `tutorials/data` folder, which has an AL block-group shapefile and NC VTD shapefile for testing. These are meant to be usable for GerryChain users who want to have access to common helpful tools that we've used for our analysis. Happy to revise any of the wording / layout of the notebooks for clarity's sake!

### CODE REVIEW

**Comment by ccthegreat313** [comment]
```
mapping = unitmap((vtd_shp, "GEOID20"), (counties, "COUNTYFP20"))
inverted_mapping = invert(mapping)
```
For this cell, could you print node 0 of mapping, just to show that keys are VTDs and values are counties?

**Comment by gabeschoenbach** [comment]
Added some of those edits, lmk what you think!

**Comment by ccthegreat313** [comment]
This looks great with the changes. Do you want to have this merged in before the TODOs are completed? If so, I'll go ahead and do that, because I'm very happy with it. Thanks for doing this!

**Comment by gabeschoenbach** [comment]
Yes let's merge it! OK to leave the TODOs for now, I think

**Comment by gabeschoenbach** [comment]
Yes let's merge it! OK to leave the TODOs for now, I think

**Pull request merged**
